In [1]:
import numpy as np

In [2]:
array=np.array([[2,4,5,8]],np.int64)

In [3]:
array[0,1]

4

In [4]:
array.shape

(1, 4)

In [5]:
array=np.array([[1,3,5],[2,4,6],[9,7,5]])

In [6]:
array

array([[1, 3, 5],
       [2, 4, 6],
       [9, 7, 5]])

In [7]:
array.dtype

dtype('int32')

In [8]:
array.shape

(3, 3)

In [9]:
array.size

9

In [10]:
zeroes=np.zeros((3,3))

In [11]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
rng=np.arange(10)

In [13]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
lspace=np.linspace(1,50,10)

In [15]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [16]:
empty=np.empty((3,3))

In [17]:
empty

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
identityMatrix=np.identity(10)

In [19]:
identityMatrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
arr=np.arange(99)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [23]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
x=[[1,3,4],[3,1,0],[2,3,1]]

In [25]:
axisarr=np.array(x)

In [26]:
axisarr

array([[1, 3, 4],
       [3, 1, 0],
       [2, 3, 1]])

In [27]:
axisarr.sum(axis=0)

array([6, 7, 5])

In [28]:
axisarr.sum(axis=1)

array([8, 4, 6])

In [29]:
axisarr.T

array([[1, 3, 2],
       [3, 1, 3],
       [4, 0, 1]])

In [30]:
onedim=np.array([2,4,5,64])

In [31]:
onedim.argmax()

3

In [32]:
onedim.argmin()

0

In [33]:
onedim.argsort()

array([0, 1, 2, 3], dtype=int64)

In [34]:
axisarr

array([[1, 3, 4],
       [3, 1, 0],
       [2, 3, 1]])

In [35]:
axisarr.argsort(axis=0)

array([[0, 1, 1],
       [2, 0, 2],
       [1, 2, 0]], dtype=int64)

In [36]:
axisarr.argsort(axis=1)

array([[0, 1, 2],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

In [37]:
axisarr

array([[1, 3, 4],
       [3, 1, 0],
       [2, 3, 1]])

In [38]:
axisar=np.array([[3,1,0],[2,2,1],[3,2,1]])

In [39]:
axisar

array([[3, 1, 0],
       [2, 2, 1],
       [3, 2, 1]])

In [40]:
axisarr+axisar

array([[4, 4, 4],
       [5, 3, 1],
       [5, 5, 2]])